data:
  dim: 2
  num_samples: 8196
  mean: [[4.0, 4.0], [-4.0, 4.0], [0., 0.]]
  std: [[0.1, 0.], [0., 0.1]]
  type: 'mixture'

model: 
  sde: VP
  layers: [3, 256, 256, 256, 256, 2]
  act: lrelu
  beta_min: 0.1
  beta_max: 20.
  num_scales: 1000
  sampling_eps: 0.001

train:
  batchsize: 128
  num_epoch: 401
  continuous: True
  save_step: 50
  eval_step: 50

optim:
  lr: 0.0005
  warmup: 5000
  grad_clip: 1.

sampling:
  method: 'pc'
  predictor: 'euler_maruyama'
  corrector: 'none'
  snr: 0.16
  n_steps_each: 1
  noise_removal: True
  probability_flow: True
  eps: 0.001
  num_samples: 8196


log:
  basedir: mixture-3mode-vp
